// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Entitiyprojecysitationeklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Entitiyprojecysitationeklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "201610272313396_Entitiy projecy sitation eklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
