//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        public Town()
        {
            this.Hospitals = new HashSet<Hospital>();
        }
    
        public int TownID { get; set; }
        public string TownName { get; set; }
        public int CityID { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Hospital> Hospitals { get; set; }
    }
}
