//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _161012_EntityFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLogin
    {
        public int UserID { get; set; }
        public long IdentitiyNumber { get; set; }
        public string Password { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
